context:
  version: "5.1.4"

package:
  name: skim
  version: ${{ version }}

source:
  url: https://github.com/skim-rs/skim/archive/v${{ version }}.tar.gz
  sha256: ae42fafdcdcce980b55eb0db3e973f248b418211b41571ccd82bbd57cd2c12b5

build:
  number: 0
  skip:
    - win
    - linux and ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sk --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fuzzy Finder in rust!
  homepage: https://github.com/skim-rs/skim
  repository: https://github.com/skim-rs/skim

extra:
  recipe-maintainers:
    - danielnachun
