context:
  version: "0.16.1"

package:
  name: skim
  version: ${{ version }}

source:
  url: https://github.com/lotabout/skim/archive/v${{ version }}.tar.gz
  sha256: c194226e9e53d216f9ea508f3152f57851e79a5e9991a89382834dbaeff6cd10

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sk --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fuzzy Finder in rust!
  homepage: https://github.com/lotabout/skim
  repository: https://github.com/lotabout/skim

extra:
  recipe-maintainers:
    - danielnachun
