context:
  version: "5.3.1"

package:
  name: skim
  version: ${{ version }}

source:
  url: https://github.com/skim-rs/skim/archive/v${{ version }}.tar.gz
  sha256: bd8298d8e232840b71e66c88249b91bf0b2e6d1aa320ad3fc405a002c521885c

build:
  number: 0
  skip:
    - win
    - linux and ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sk --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fuzzy Finder in rust!
  homepage: https://github.com/skim-rs/skim
  repository: https://github.com/skim-rs/skim

extra:
  recipe-maintainers:
    - danielnachun
