context:
  version: "0.20.4"

package:
  name: skim
  version: ${{ version }}

source:
  url: https://github.com/lotabout/skim/archive/v${{ version }}.tar.gz
  sha256: a1309f9cc10b287673c3c1067490888b9116a30a84d9c202401cdf1798982a28

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sk --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fuzzy Finder in rust!
  homepage: https://github.com/lotabout/skim
  repository: https://github.com/lotabout/skim

extra:
  recipe-maintainers:
    - danielnachun
