context:
  version: "4.10.0"

package:
  name: skim
  version: ${{ version }}

source:
  url: https://github.com/skim-rs/skim/archive/v${{ version }}.tar.gz
  sha256: 0f77826fe73b4ad69bc692bd3407156fec3ffde12b270472d933de13bf3bd1e7

build:
  number: 0
  skip:
    - win
    - linux and ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sk --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fuzzy Finder in rust!
  homepage: https://github.com/skim-rs/skim
  repository: https://github.com/skim-rs/skim

extra:
  recipe-maintainers:
    - danielnachun
