context:
  version: "3.5.0"

package:
  name: skim
  version: ${{ version }}

source:
  url: https://github.com/skim-rs/skim/archive/v${{ version }}.tar.gz
  sha256: df0faf2530ce999c3ab64d8dcde71601f6c3381434aa30fdfd3f9fd6702b8840

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sk --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fuzzy Finder in rust!
  homepage: https://github.com/skim-rs/skim
  repository: https://github.com/skim-rs/skim

extra:
  recipe-maintainers:
    - danielnachun
